var projectList = { "projects": [
    {
        header: "Team Florida Logo",
        year: 2012,
        city: "Miami, FL",
        image: "../img/project_img/Florida_roller_derby_2012_logo.jpg",
        alt: "Team Florida Logo",
        imageZoom: "45%",
        descr: "Logo created for Team Florida Roller Derby. Debuted at Rollercon 2012 for Team Florida vs Team Texas Exhibition Bout.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Gold Coast Schedule",
        year: 2013,
        city: "Ft. Lauderdale, FL",
        image: "../img/project_img/GCDG_Schedule_2013.png",
        alt: "Team Schedule Design",
        imageZoom: "76%",
        descr: "Gold Coast Derby Grrls Schedule Design for 5x7 Postcards",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Windy City Posters",
        year: 2015,
        city: "Chicago, IL",
        image: "../img/project_img/WCR_Poster_2015.png",
        alt: "WCR Poster",
        imageZoom: "70%",
        descr: "Season poster design for Windy City Rollers. Printed size 11x17.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Africa US Today",
        year: 2015,
        city: "Chicago, IL",
        image: "../img/project_img/Africa_US_today_logo_2015.png",
        alt: "Africa US Logo",
        imageZoom: "46%",
        descr: "Logo created for Africa US Today, an online magazine.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "World AIDS Day Poster",
        year: 2015,
        city: "Chicago, IL",
        image: "../img/project_img/WorldAids_1_NEIU_2015.png",
        alt: "World Aids Poster - White",
        imageZoom: "70%",
        descr: "1 of 2 posters created for NEIU's Angelina Pedroso Center for Diversity and Intercultural Affairs. One of my graduate assistantship responsibilities. Printed size 17x11",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "World AIDS Day Poster",
        year: 2015,
        city: "Chicago, IL",
        image: "../img/project_img/WorldAids_1_NEIU_2015_small.png",
        alt: "World Aids Poster - Dark",
        imageZoom: "60%",
        descr: "2 of 2 posters created for NEIU's Angelina Pedroso Center for Diversity and Intercultural Affairs. One of my graduate assistantship responsibilities. Printed size 8.5x11",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Black and Blue Gala",
        year: 2015,
        city: "Chicago, IL",
        image: "../img/project_img/wcr_blackandblue_2014.png",
        alt: "Gala Poster",
        imageZoom: "70%",
        descr: "Windy City Rollers Black and Blue Gala poster design to celebrate 10 year anniversary. Printed size 11x17",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "The Field Bistro",
        year: 2016,
        city: "Chicago, IL",
        image: "../img/project_img/FieldMuseum_Birstro_Menus_2016.png",
        alt: "Bistro Menus",
        imageZoom: "60%",
        descr: "Custom hand menu's created for The Field Museum of Natural History's Field Bistro. Printed size 5.5x8.5",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Wall Menu",
        year: 2016,
        city: "Chicago, IL",
        image: "../img/project_img/FieldMuseum_FieldBistro_PVC_2016.png",
        alt: "Wall Menu",
        imageZoom: "50%",
        descr: "Custom wall menu created for The Field Museum of Natural History's Field Bistro. Printed size 45.5x50",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Tank Rampage",
        year: 2016,
        city: "Chicago, IL",
        image: "../img/project_img/tankRampage.png",
        alt: "Tank Rampage",
        imageZoom: "50%",
        descr: "CS 417 - Video Game Programming Final Project, Developed By Amanda J. Kendal-Brown & Abdulhai Almontashri. Built with previous version of Unity.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " | ",
        projectLink: "<a class='projectExternal_Links' href='BuildFiles/TankRampage.html' target='_blank'>See Project</a>",
        spacer2: " | ",
        githubLink: "<a class='projectExternal_Links' href='https://github.com/ajkendal/TankRampage' target='_blank'>Repository</a>"
    },
    {
        header: "Pycon Poster",
        year: 2016,
        city: "Chicago, IL",
        image: "../img/project_img/PyConPoster_5_2016.png",
        alt: "Pycon Poster",
        imageZoom: "50%",
        descr: "Poster design created for Josh Shields. Displayed at Pycon 2016",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " | ",
        projectLink: "<a class='projectExternal_Links' href='https://us.pycon.org/2016/schedule/presentation/2013/' target='_blank'>See Project</a>",
        spacer2: " | ",
        githubLink: "<a class='projectExternal_links' href='https://github.com/jshields/py_sitemapper' target='_blank'>Repository</a>"
    },
    {
        header: "Lakeside Pride",
        year: 2017,
        city: "Chicago, IL",
        image: "../img/project_img/LakesidePride_2017_Season.png",
        alt: "Lakeside Pride",
        imageZoom: "45%",
        descr: "Lakeside Pride Music Ensembles marketing design for the 2017 - 2018 season. Theme is Unity & Resistance.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    },
    {
        header: "Nerdery Hackathon",
        year: 2017,
        city: "Chicago, IL",
        image: "../img/project_img/uhOhProject_Hackathon.png",
        alt: "Hackathon",
        imageZoom: "50%",
        descr: "2nd place winner for Nerd Immersion Hackathon, Oh NO! My car got towed! is a web application that helps users find cars towed in the City of Chicago.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " | ",
        projectLink: "<a class='projectExternal_Links' href='https://heymarcy.github.io/chi_towed_cars/' target='_blank'>See Project</a>",
        spacer2: " | ",
        githubLink: "<a class='projectExternal_links' href='https://github.com/HeyMarcy/chi_towed_cars' target='_blank'>Repository</a>"
    },
    {
        header: "Blaque Jac",
        year: 2017,
        city: "Atlanta, GA",
        image: "../img/project_img/BlaqueJac.png",
        alt: "Blaque Jac",
        imageZoom: "50%",
        descr: "Personal project requested by a fellow friend of mine.",
        imageLink: "<a href='#fullImageClass' class='fullImageLink'>Full Image</a>",
        spacer1: " ",
        projectLink: " ",
        spacer2: " ",
        githubLink: " "
    }
]};